- name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host:     ${{ secrets.EC2_HOST }}
          username: ec2-user
          key:      ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws ecr get-login-password --region ap-southeast-2 | \
              docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

            docker pull ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest

            docker stop astronova-api || true
            docker rm astronova-api   || true

            docker run -d \
              --name astronova-api \
              --restart unless-stopped \
              -p 8000:8000 \
              -v /home/ec2-user/best_model.pt:/app/models/best_model.pt \
              -e NASA_API_KEY=${{ secrets.NASA_API_KEY }} \
              -e MLFLOW_TRACKING_URI=sqlite:///mlflow.db \
              ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest
